# serverless.yml

service: taxi-service
configValidationMode: warn

provider:
  name: aws
  runtime: python3.9
  stage: dev # Default stage to be used. Default is "dev"
  region: us-east-1 # Default region to be used. Default is "us-east-1"
  stackName: serverless-taxi-stack # Use a custom name for the CloudFormation stack
  apiName: taxi-api-gateway # Use a custom name for the API Gateway API
  lambdaHashingVersion: 20201221

  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
    tags: # Tags that will be added to each of the deployment resources
      app: taxi
    deploymentPrefix: serverless

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: app/models.app
    packRequirements: false

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'

functions:
   base: # The lambda Function name
    handler: wsgi_handler.handler
    runtime: python3.9
    role: arn:aws:iam::428938486474:role/service-role/lambda-cloud-project-role # IAM role which will be used for this function
    events: # The Events that trigger this Function
      - http: GET /
      - http: GET /taxi/{shift_id}
      - http: GET /taxi/specialEvent
      - http: GET /boundary
      - http: GET /locations
      - http: GET /newRequests
      - http: GET /taxi/migrate
      - http: POST /bookTaxi
      - http: POST /bookTaxi/confirm
      - http: POST /stream